import type { EngineReport } from "./engine";
import type { Analysis, RevisedAssignment } from "./schema";

/**
 * Builds the file an educator actually takes away: the revised assignment they
 * can paste straight into their LMS, followed by the record of what changed and
 * the measurements behind it.
 */
export function buildSummary(
  revised: RevisedAssignment,
  objective: string,
  analysis: Analysis,
  report: EngineReport,
  score: number
): string {
  const lines: string[] = [];

  lines.push(`# ${revised.title}`, "");
  lines.push("## Revised assignment", "");
  lines.push("*Ready to paste into your LMS.*", "");
  lines.push(revised.revisedText.trim(), "");
  lines.push("---", "");

  lines.push("## Learning objective (unchanged)", "");
  lines.push(objective, "");

  lines.push("## What changed, and why", "");
  if (revised.changes.length === 0) {
    lines.push("No changes were applied.", "");
  } else {
    for (const change of revised.changes) {
      lines.push(`- **${change.what}**`, `  ${change.why}`, "");
    }
  }

  lines.push("## Measurements before repair", "");
  lines.push(`- Task accessibility confidence: ${score}/100`);
  lines.push(
    `- Peak working-memory load: ${report.memory.peakLoad} item(s) held at once (capacity is about ${report.memory.capacity} chunks, Cowan 2001)`
  );
  const decay = report.memory.carried.filter((item) => item.decayRisk).length;
  if (decay > 0) {
    lines.push(`- ${decay} value(s) had to survive an environment change unaided`);
  }
  lines.push(
    `- Context switching: ${report.switching.transitions} transition(s) across ${report.switching.uniqueEnvironments.length} environments`
  );
  if (report.timing.timeLimitMinutes !== null) {
    lines.push(
      `- Timing: about ${report.timing.requiredMinutesMean} minutes of reading and actions against a ${report.timing.timeLimitMinutes}-minute limit (${report.timing.verdict}); a slower reader needs about ${report.timing.requiredMinutesConservative} minutes`
    );
  } else {
    lines.push(`- Timing: no limit imposed`);
  }
  lines.push(
    `- Instructions: grade ${report.text.fleschKincaidGrade} reading level, ${report.text.instructionDensity} instruction(s) in the densest paragraph`
  );
  lines.push("", `- Friction moments identified: ${analysis.frictionMoments.length}`);
  lines.push("");

  lines.push("---", "");
  lines.push(
    "Measurements are computed from the task structure, not generated. This reflects task-level accessibility friction, not legal compliance, and educator judgment remains part of every decision.",
    ""
  );
  lines.push("Generated by AccessLens.");

  return lines.join("\n");
}

export function downloadSummary(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function summaryFilename(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `${slug || "assignment"}-accesslens.md`;
}
